controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

login:
    path: /login
    controller: App\Controller\SecurityController::login

index:
    path: /index
    defaults:
        _controller: App\Controller\BookBinderController::index
home:
    path: /home
    defaults:
        _controller: App\Controller\BookBinderController::index

handle-dropdown-selection:
  path: /handle-dropdown-selection
  controller: App\Controller\SearchController::handleDropdownSelection

